- hosts: 3.111.53.174
  become: true
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/cluster01.yml
    - name: create new service
      command: kubectl apply -f /home/ubuntu/service01.yml
